import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { formatBuildDate, nextBuildId, runGit } from "./build-id.ts";

const subjects = (runGit(["log", "--format=%s"]) ?? "").split(/\r?\n/).filter(Boolean);
const buildId = nextBuildId(formatBuildDate(new Date()), subjects);
const target = resolve(process.cwd(), "src/generated/build-metadata.ts");

writeFileSync(
  target,
  `// Generated by \`npm run version:stamp\` before each release commit.\nexport const SOURCE_BUILD_ID = "${buildId}";\n`,
  "utf8",
);

console.log(buildId);
