/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTarefasRouteImport } from './routes/app.tarefas'
import { Route as AppPontoRouteImport } from './routes/app.ponto'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppNotasRouteImport } from './routes/app.notas'
import { Route as AppFrotaRouteImport } from './routes/app.frota'
import { Route as AppFeriasRouteImport } from './routes/app.ferias'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppEmpresaRouteImport } from './routes/app.empresa'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAssistenteRouteImport } from './routes/app.assistente'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppPontoRoute = AppPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaRoute = AppFrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => AppRoute,
} as any)
const AppFeriasRoute = AppFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/ferias': typeof AppFeriasRoute
  '/app/frota': typeof AppFrotaRoute
  '/app/notas': typeof AppNotasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ponto': typeof AppPontoRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/ferias': typeof AppFeriasRoute
  '/app/frota': typeof AppFrotaRoute
  '/app/notas': typeof AppNotasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ponto': typeof AppPontoRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/ferias': typeof AppFeriasRoute
  '/app/frota': typeof AppFrotaRoute
  '/app/notas': typeof AppNotasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ponto': typeof AppPontoRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/admin'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/empresa'
    | '/app/equipe'
    | '/app/ferias'
    | '/app/frota'
    | '/app/notas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/ponto'
    | '/app/tarefas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/login'
    | '/reset-password'
    | '/app/admin'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/empresa'
    | '/app/equipe'
    | '/app/ferias'
    | '/app/frota'
    | '/app/notas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/ponto'
    | '/app/tarefas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/aceitar-convite'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/admin'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/empresa'
    | '/app/equipe'
    | '/app/ferias'
    | '/app/frota'
    | '/app/notas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/ponto'
    | '/app/tarefas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AceitarConviteRoute: typeof AceitarConviteRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas': {
      id: '/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ponto': {
      id: '/app/ponto'
      path: '/ponto'
      fullPath: '/app/ponto'
      preLoaderRoute: typeof AppPontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas': {
      id: '/app/notas'
      path: '/notas'
      fullPath: '/app/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota': {
      id: '/app/frota'
      path: '/frota'
      fullPath: '/app/frota'
      preLoaderRoute: typeof AppFrotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ferias': {
      id: '/app/ferias'
      path: '/ferias'
      fullPath: '/app/ferias'
      preLoaderRoute: typeof AppFeriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresa': {
      id: '/app/empresa'
      path: '/empresa'
      fullPath: '/app/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistente': {
      id: '/app/assistente'
      path: '/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppClientesRoute: typeof AppClientesRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFeriasRoute: typeof AppFeriasRoute
  AppFrotaRoute: typeof AppFrotaRoute
  AppNotasRoute: typeof AppNotasRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPontoRoute: typeof AppPontoRoute
  AppTarefasRoute: typeof AppTarefasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAssistenteRoute: AppAssistenteRoute,
  AppClientesRoute: AppClientesRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFeriasRoute: AppFeriasRoute,
  AppFrotaRoute: AppFrotaRoute,
  AppNotasRoute: AppNotasRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPontoRoute: AppPontoRoute,
  AppTarefasRoute: AppTarefasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AceitarConviteRoute: AceitarConviteRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
